project:
  type: website
  output-dir: docs

website:
  title: "codebrew404"
  navbar:
    logo: images/CodeBrew404Logo.jpg
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    search: true
    tools:
      - icon: github
        href:  https://github.com/codebrew404
        target: _blank
      - icon: youtube
        href: https://www.youtube.com/@codebrew404
        target: _blank

format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css



